export const states = [
  "03-PUNJAB",
  "Bihar",
  "CHATTISGARH",
  "DELHI",
  "EAST MP",
  "EAST UP",
  "GUJARAT",
  "HARYANA",
  "JHARKHAND",
  "North East",
  "ODISHA",
  "RAJASTHAN",
  "WEST BENGAL",
  "WEST MP",
  "WEST UP",
];
// export const states = [
//   "Andhra Pradesh",
//   "Arunachal Pradesh",
//   "Assam",
//   "Bihar",
//   "Chhattisgarh",
//   "Goa",
//   "Gujarat",
//   "Haryana",
//   "Himachal Pradesh",
//   "Jharkhand",
//   "Karnataka",
//   "Kerala",
//   "Madhya Pradesh",
//   "Maharashtra",
//   "Manipur",
//   "Meghalaya",
//   "Mizoram",
//   "Nagaland",
//   "Odisha",
//   "Punjab",
//   "Rajasthan",
//   "Sikkim",
//   "Tamil Nadu",
//   "Telangana",
//   "Tripura",
//   "Uttar Pradesh",
//   "Uttarakhand",
//   "West Bengal",
// ];
